export const GENRES = {
  POP: "Pop",
  REGGAETON: "Reggaeton",
  ROCK: "Rock",
  CLASSICAL: "Classical",
  MISC: "Miscellaneous",
  HOUSE: "Electro House",
  BIGROOM: "Big Room",
  HARDSTYLE: "Hardstyle",
  DUBSTEP: "Dupstep",
  TRANCE: "Trance",
  TECHNO: "Techno",
}

const genresMap: Record<string, string> = {
  "pop": GENRES.POP,
  "pop dance": GENRES.POP,
  "dance pop": GENRES.POP,
  "urbano latino": GENRES.REGGAETON,
  "reggaeton": GENRES.REGGAETON,
  "trap latino": GENRES.REGGAETON,
  "latin pop": GENRES.REGGAETON,
  "reggaeton colombiano": GENRES.REGGAETON,
  "pop rap": GENRES.POP,
  "rap": GENRES.POP,
  "uk pop": GENRES.POP,
  "rock": GENRES.ROCK,
  "pop argentino": GENRES.REGGAETON,
  "modern rock": GENRES.ROCK,
  "romanian pop": GENRES.POP,
  "latin viral pop": GENRES.POP,
  "colombian pop": GENRES.POP,
  "pop edm": GENRES.POP,
  "canadian pop": GENRES.POP,
  "rap latina": GENRES.POP,
  "latin hip hop": GENRES.POP,
  "miami hip hop": GENRES.POP,
  "urban contemporary": GENRES.POP,
  "swedish pop": GENRES.POP,
  "art pop": GENRES.POP,
  "puerto rican pop": GENRES.POP,
  "post-teen pop": GENRES.POP,
  "australian pop": GENRES.POP,
  "pop nacional": GENRES.POP,
  "modern indie pop": GENRES.POP,
  "atl hip hop": GENRES.POP,
  "trap": GENRES.POP,
  "hip pop": GENRES.POP,
  "queens hip hop": GENRES.POP,
  "r&b": GENRES.POP,
  "trap argentino": GENRES.REGGAETON,
  "classic rock": GENRES.ROCK,
  "mexican pop": GENRES.POP,
  "reggaeton flow": GENRES.REGGAETON,
  "pov: indie": GENRES.POP,
  "singer-songwriter pop": GENRES.POP,
  "classical": GENRES.CLASSICAL,
  "spanish pop": GENRES.POP,
  "southern hip hop": GENRES.POP,
  "norwegian pop": GENRES.POP,
  "barbadian pop": GENRES.POP,
  "piano rock": GENRES.ROCK,
  "reggae fusion": GENRES.POP,
  "canadian contemporary r&b": GENRES.POP,
  "argentine hip hop": GENRES.POP,
  "viral pop": GENRES.POP,
  "pop soul": GENRES.POP,
  "french pop": GENRES.POP,
  "corridos tumbados": GENRES.REGGAETON,
  "sad sierreno": GENRES.REGGAETON,
  "funk pop": GENRES.POP,
  "latin arena pop": GENRES.POP,
  "la pop": GENRES.POP,
  "ohio hip hop": GENRES.POP,
  "modern alternative rock": GENRES.ROCK,
  "latin alternative": GENRES.REGGAETON,
  "latin rock": GENRES.ROCK,
  "rock en espanol": GENRES.ROCK,
  "modern alternative pop": GENRES.POP,
  "indie poptimism": GENRES.POP,
  "british soul": GENRES.POP,
  "nz pop": GENRES.POP,
  "glam rock": GENRES.ROCK,
  "spanish pop rock": GENRES.ROCK,
  "psychedelic rock": GENRES.ROCK,
  "urbano mexicano": GENRES.REGGAETON,
  "electro latino": GENRES.REGGAETON,
  "uk contemporary r&b": GENRES.POP,
  "crunk": GENRES.POP,
  "rap canario": GENRES.POP,
  "contemporary r&b": GENRES.POP,
  "south carolina hip hop": GENRES.POP,
  "neo mellow": GENRES.POP,
  "pop rock": GENRES.ROCK,
  "nz hip hop": GENRES.POP,
  "gangster rap": GENRES.POP,
  "trap triste": GENRES.REGGAETON,
  "k-pop": GENRES.POP,
  "baroque pop": GENRES.POP,
  "boy band": GENRES.POP,
  "neo soul": GENRES.POP,
  "new romantic": GENRES.POP,
  "new wave": GENRES.ROCK,
  "new wave pop": GENRES.POP,
  "synthpop": GENRES.POP,
  "album rock": GENRES.ROCK,
  "soft rock": GENRES.ROCK,
  "europop": GENRES.POP,
  "melodic rap": GENRES.POP,
  "r&b en espanol": GENRES.POP,
  "early romantic era": GENRES.CLASSICAL,
  "polish classical": GENRES.CLASSICAL,
  "classical piano": GENRES.CLASSICAL,
  "polish classical piano": GENRES.CLASSICAL,
  "scandipop": GENRES.POP,
  "late romantic era": GENRES.CLASSICAL,
  "russian modern classical": GENRES.CLASSICAL,
  "german pop": GENRES.POP,
  "british invasion": GENRES.ROCK,
  "merseybeat": GENRES.ROCK,
  "baroque": GENRES.CLASSICAL,
  "german baroque": GENRES.CLASSICAL,
  "orchestral performance": GENRES.CLASSICAL,
  "new age piano": GENRES.CLASSICAL,
  "girl group": GENRES.POP,
  "indonesian pop": GENRES.POP,
  "k-pop girl group": GENRES.POP,
  "dutch pop": GENRES.POP,
  "dirty south rap": GENRES.POP,
  "old school atlanta hip hop": GENRES.POP,
  "emo": GENRES.ROCK,
  "bass trap": GENRES.REGGAETON,
  "modern salsa": GENRES.REGGAETON,
  "salsa": GENRES.REGGAETON,
  "tropical": GENRES.REGGAETON,
  "nyc rap": GENRES.POP,
  "guaracha": GENRES.REGGAETON,
  "swedish indie pop": GENRES.POP,
  "k-pop boy group": GENRES.POP,
  "deep dance pop": GENRES.POP,
  "punk": GENRES.ROCK,
  "nigerian pop": GENRES.POP,
  "reggae": GENRES.POP,
  "viral trap": GENRES.REGGAETON,
  "uk alternative pop": GENRES.POP,
  "candy pop": GENRES.POP,
  "alternative hip hop": GENRES.POP,
  "underground hip hop": GENRES.POP,
  "neo-synthpop": GENRES.POP,
  "new jersey underground rap": GENRES.POP,
  "trap queen": GENRES.REGGAETON,
  "nyc pop": GENRES.POP,
  "alternative r&b": GENRES.POP,
  "alternative rock": GENRES.ROCK,
  "indie rock": GENRES.ROCK,
  "r&b argentino": GENRES.POP,
  "modern hard rock": GENRES.ROCK,
  "danish pop": GENRES.POP,
  "art rock": GENRES.ROCK,
  "beatlesque": GENRES.ROCK,
  "mellow gold": GENRES.POP,
  "symphonic rock": GENRES.ROCK,
  "grunge": GENRES.ROCK,
  "australian hip hop": GENRES.POP,
  "german pop rock": GENRES.ROCK,
  "classic schlager": GENRES.POP,
  "belgian pop": GENRES.POP,
  "dance rock": GENRES.ROCK,
  "sophisti-pop": GENRES.POP,
  "singer-songwriter": GENRES.POP,
  "rock keyboard": GENRES.ROCK,
  "seattle hip hop": GENRES.POP,
  "north carolina hip hop": GENRES.POP,
  "pop venezolano": GENRES.POP,
  "memphis hip hop": GENRES.POP,
  "bubblegum pop": GENRES.POP,
  "folk rock": GENRES.ROCK,
  "rock-and-roll": GENRES.ROCK,
  "rockabilly": GENRES.ROCK,
  "hard rock": GENRES.ROCK,
  "traprun": GENRES.REGGAETON,
  "chill abstract hip hop": GENRES.POP,
  "indie hip hop": GENRES.POP,
  "neon pop punk": GENRES.ROCK,
  "pop punk": GENRES.ROCK,
  "taiwan classical performance": GENRES.CLASSICAL,
  "violin": GENRES.CLASSICAL,
  "panamanian pop": GENRES.POP,
  "asian american hip hop": GENRES.POP,
  "estonian pop": GENRES.POP,
  "indie pop rap": GENRES.POP,
  "irish pop": GENRES.POP,
  "atl trap": GENRES.POP,
  "edm": GENRES.HOUSE,
  "electro house": GENRES.HOUSE,
  "big room": GENRES.BIGROOM,
  "progressive electro house": GENRES.HOUSE,
  "dutch house": GENRES.HOUSE,
  "slap house": GENRES.HOUSE,
  "progressive house": GENRES.HOUSE,
  "dutch edm": GENRES.BIGROOM,
  "brostep": GENRES.DUBSTEP,
  "indian edm": GENRES.BIGROOM,
  "house": GENRES.HOUSE,
  "australian dance": GENRES.HOUSE,
  "melbourne bounce": GENRES.HOUSE,
  "melbourne bounce international": GENRES.HOUSE,
  "gaming edm": GENRES.HOUSE,
  "uk dance": GENRES.HOUSE,
  "hypertechno": GENRES.TECHNO,
  "trance": GENRES.TRANCE,
  "complextro": GENRES.HOUSE,
  "romanian house": GENRES.HOUSE,
  "belgian edm": GENRES.HOUSE,
  "dutch trance": GENRES.TRANCE,
  "nordic house": GENRES.HOUSE,
  "indietronica": GENRES.HOUSE,
  "belgian dance": GENRES.HOUSE,
  "swedish electropop": GENRES.POP,
  "german techno": GENRES.TECHNO,
  "electro": GENRES.HOUSE,
  "electropop": GENRES.POP,
  "swedish synthpop": GENRES.POP,
  "italo dance": GENRES.HOUSE,
  "tropical house": GENRES.HOUSE,
  "classic hardstyle": GENRES.HARDSTYLE,
  "euphoric hardstyle": GENRES.HARDSTYLE,
  "brazilian edm": GENRES.HOUSE,
  "german dance": GENRES.HOUSE,
  "future house": GENRES.HOUSE,
  "dancehall": GENRES.HOUSE,
  "moombahton": GENRES.HOUSE,
  "electronica argentina": GENRES.HOUSE,
  "pop electronico": GENRES.POP,
  "russian dance": GENRES.HOUSE,
  "progressive uplifting trance": GENRES.TRANCE,
  "aussietronica": GENRES.HOUSE,
  "deep euro house": GENRES.HOUSE,
  "epicore": GENRES.HOUSE,
  "canadian electronic": GENRES.HOUSE,
  "russian edm": GENRES.HOUSE,
  "mexican edm": GENRES.HOUSE,
  "berlin minimal techno": GENRES.TECHNO,
  "rawstyle": GENRES.HARDSTYLE,
  "classic dubstep": GENRES.DUBSTEP,
  "dubstep": GENRES.DUBSTEP,
  "gaming dubstep": GENRES.DUBSTEP,
  "uplifting trance": GENRES.TRANCE,
  "danish electronic": GENRES.HOUSE,
  "circuit": GENRES.HOUSE,
  "deep house": GENRES.HOUSE,
  "turkish deep house": GENRES.HOUSE,
  "turkish edm": GENRES.HOUSE,
  "hands up": GENRES.HOUSE,
  "bass house": GENRES.HOUSE,
  "tech house": GENRES.HOUSE,
  "pinoy edm": GENRES.HOUSE,
  "canadian electropop": GENRES.POP,
  "disco house": GENRES.HOUSE,
  "vocal house": GENRES.HOUSE,
  "diva house": GENRES.HOUSE,
  "g-house": GENRES.HOUSE,
  "finnish edm": GENRES.HOUSE,
  "dancefloor dnb": GENRES.HOUSE,
  "deep tropical house": GENRES.HOUSE,
  "experimental bass": GENRES.HOUSE,
  "swedish eurodance": GENRES.HOUSE,
  "trancecore": GENRES.TRANCE,
  "glitch hop": GENRES.BIGROOM,
  "bossbeat": GENRES.HOUSE,
  "deep pop edm": GENRES.POP,
};


export const getGeneralGenre = (genre: string) => genresMap[genre];